name: Update KDE Connect Cask

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  update-cask:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for updates
        id: check
        run: |
          # Get latest ARM64 build URL
          ARM64_FILENAME=$(curl -s https://cdn.kde.org/ci-builds/network/kdeconnect-kde/master/macos-arm64/ | grep -o 'href="[^"]*\.dmg"' | grep -o '"[^"]*"' | tr -d '"' | sort -r | head -1)
          ARM64_URL="https://cdn.kde.org/ci-builds/network/kdeconnect-kde/master/macos-arm64/$ARM64_FILENAME"
          
          # Extract build number more flexibly - look for any number that appears to be a build ID
          ARM64_BUILD=$(echo "$ARM64_FILENAME" | grep -o '[0-9]\{4,\}' | head -1)
          if [ -z "$ARM64_BUILD" ]; then
            # Fallback: try to extract any number that might be a build number
            ARM64_BUILD=$(echo "$ARM64_FILENAME" | grep -o '[0-9]*' | grep -v '^[0-9]\{1,3\}$' | head -1)
          fi
          
          # Get latest x86_64 build URL
          X86_FILENAME=$(curl -s https://cdn.kde.org/ci-builds/network/kdeconnect-kde/master/macos-x86_64/ | grep -o 'href="[^"]*\.dmg"' | grep -o '"[^"]*"' | tr -d '"' | sort -r | head -1)
          X86_URL="https://cdn.kde.org/ci-builds/network/kdeconnect-kde/master/macos-x86_64/$X86_FILENAME"
          
          # Extract build number more flexibly - look for any number that appears to be a build ID
          X86_BUILD=$(echo "$X86_FILENAME" | grep -o '[0-9]\{4,\}' | head -1)
          if [ -z "$X86_BUILD" ]; then
            # Fallback: try to extract any number that might be a build number
            X86_BUILD=$(echo "$X86_FILENAME" | grep -o '[0-9]*' | grep -v '^[0-9]\{1,3\}$' | head -1)
          fi
          
          echo "Latest ARM64 build: $ARM64_BUILD"
          echo "Latest x86_64 build: $X86_BUILD"
          echo "ARM64 URL: $ARM64_URL"
          echo "x86_64 URL: $X86_URL"
          
          # Use the higher build number as the version
          if [ "$ARM64_BUILD" -gt "$X86_BUILD" ]; then
            NEW_VERSION="$ARM64_BUILD"
          else
            NEW_VERSION="$X86_BUILD"
          fi
          
          # Get current version from cask (handle case where version line doesn't exist)
          CURRENT_VERSION=$(grep -o 'version "[0-9]*"' Casks/kdeconnect.rb | grep -o '[0-9]*' || echo "0")
          echo "Current version in cask: $CURRENT_VERSION"
          echo "New version found: $NEW_VERSION"
          
          if [ "$NEW_VERSION" != "" ] && [ "$NEW_VERSION" != "$CURRENT_VERSION" ]; then
            echo "New version available: $NEW_VERSION"
            echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "arm64_url=$ARM64_URL" >> $GITHUB_OUTPUT
            echo "x86_url=$X86_URL" >> $GITHUB_OUTPUT
            echo "update_needed=true" >> $GITHUB_OUTPUT
          else
            echo "No update needed"
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update cask
        if: steps.check.outputs.update_needed == 'true'
        run: |
          # Get the actual URLs from the check step
          ARM64_URL="${{ steps.check.outputs.arm64_url }}"
          X86_URL="${{ steps.check.outputs.x86_url }}"
          NEW_VERSION="${{ steps.check.outputs.new_version }}"
          
          echo "Updating cask with:"
          echo "  ARM64 URL: $ARM64_URL"
          echo "  x86_64 URL: $X86_URL"
          echo "  Version: $NEW_VERSION"
          
          # Update ARM64 URL - escape the URL for sed
          ARM64_URL_ESCAPED=$(echo "$ARM64_URL" | sed 's/[[\.*^$()+?{|]/\\&/g')
          # Replace the entire ARM64 URL line with the new URL
          sed -i "/url \".*arm64.*dmg\"/c\      url \"$ARM64_URL_ESCAPED\"" Casks/kdeconnect.rb
          
          # Update x86_64 URL - escape the URL for sed
          X86_URL_ESCAPED=$(echo "$X86_URL" | sed 's/[[\.*^$()+?{|]/\\&/g')
          # Replace the entire x86_64 URL line with the new URL
          sed -i "/url \".*x86_64.*dmg\"/c\      url \"$X86_URL_ESCAPED\"" Casks/kdeconnect.rb
          
          # Update version
          sed -i "s|version \"[0-9]*\"|version \"$NEW_VERSION\"|" Casks/kdeconnect.rb

      - name: Create Pull Request
        if: steps.check.outputs.update_needed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Install GitHub CLI only if not already present
          if ! command -v gh &> /dev/null; then
            echo "Installing GitHub CLI..."
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y gh
          else
            echo "GitHub CLI already installed"
          fi
          
          # Configure git
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Create branch and commit
          git checkout -b update-kdeconnect-${{ steps.check.outputs.new_version }}
          git add Casks/kdeconnect.rb
          git commit -m "Update KDE Connect to version ${{ steps.check.outputs.new_version }}"
          git push -f origin update-kdeconnect-${{ steps.check.outputs.new_version }}
          
          # Create PR
          PR_URL=$(gh pr create \
            --title "Update KDE Connect to version ${{ steps.check.outputs.new_version }}" \
            --body "This automated PR updates the KDE Connect cask to version ${{ steps.check.outputs.new_version }}.

            - Updated via Homebrew livecheck
            - Version: ${{ steps.check.outputs.new_version }}" \
            --head update-kdeconnect-${{ steps.check.outputs.new_version }} \
            --base main)
          
          if [ $? -eq 0 ] && [ -n "$PR_URL" ]; then
            echo "Created PR: $PR_URL"
            
            # Extract PR number from URL
            PR_NUMBER=$(echo $PR_URL | grep -o '[0-9]*$')
            
            if [ -n "$PR_NUMBER" ]; then
              # Enable automerge
              gh pr merge $PR_NUMBER --auto --merge || echo "Auto-merge not enabled. You may need to configure branch protection rules."
              echo "PR #$PR_NUMBER is ready for auto-merge (will merge when tests pass)"
            else
              echo "Could not extract PR number from URL: $PR_URL"
            fi
          else
            echo "PR creation failed or PR already exists"
          fi

      - name: Skip if no update
        if: steps.check.outputs.update_needed == 'false'
        run: echo "No update needed, skipping PR creation" 